import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { QueryClientProvider, getqueryClient } from "@/lib/getQuerry";
import Providers from "@/components/Providers";
import ShoppingCartModal from "@/components/ShoppingCartModal";





const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"suppressHydrationWarning >
      <body className={inter.className}>
         <Providers>
         <QueryClientProvider client={getqueryClient}>
         <Navbar/>
         <ShoppingCartModal/>
         {children}
        </QueryClientProvider>
        </Providers>
        </body>
    </html>
  );
}
